(function(){if("undefined"===typeof kintInitialized){kintInitialized=1;var e=[],f=-1,g=function(b){var a=window.getSelection(),c=document.createRange();c.selectNodeContents(b);a.removeAllRanges();a.addRange(c)},h=function(b){Array.prototype.slice.call(document.querySelectorAll(".kint nav, .kint-tabs>li:not(.kint-active-tab)"),0).forEach(b)},k=function(b,a){"undefined"===typeof a&&(a="kint-show");return RegExp("(\\s|^)"+a+"(\\s|$)").test(b.className)},m=function(b,a){"undefined"===typeof a&&(a="kint-show");l(b,
a).className+=" "+a},l=function(b,a){"undefined"===typeof a&&(a="kint-show");b.className=b.className.replace(RegExp("(\\s|^)"+a+"(\\s|$)")," ");return b},n=function(b){do b=b.nextElementSibling;while("dd"!==b.nodeName.toLowerCase());return b},p=function(b,a){var c=n(b);"undefined"===typeof a&&(a=k(b));a?l(b):m(b);1===c.childNodes.length&&(c=c.childNodes[0].childNodes[0],k(c,"kint-parent")&&p(c,a))},r=function(b,a){var c=n(b).getElementsByClassName("kint-parent"),d=c.length;for("undefined"===typeof a&&
(a=k(b));d--;)p(c[d],a);p(b,a)},s=function(b){var a=b,c=0;b.parentNode.getElementsByClassName("kint-active-tab")[0].className="";for(b.className="kint-active-tab";a=a.previousSibling;)1===a.nodeType&&c++;b=b.parentNode.nextSibling.childNodes;for(var d=0;d<b.length;d++)d===c?(b[d].style.display="block",1===b[d].childNodes.length&&(a=b[d].childNodes[0].childNodes[0],k(a,"kint-parent")&&p(a,!1))):b[d].style.display="none"},t=function(b){for(;b=b.parentNode,b&&!k(b,"kint"););return!!b},u=function(){e=
[];h(function(b){0===b.offsetWidth&&0===b.offsetHeight||e.push(b)})},v=function(b){var a;if(a=window.open())a.document.open(),a.document.write("<html><head><title>Kint ("+(new Date).toISOString()+')</title><meta charset="utf-8">'+document.getElementsByClassName("-kint-js")[0].outerHTML+document.getElementsByClassName("-kint-css")[0].outerHTML+'</head><body><input style="width: 100%" placeholder="Take some notes!"><div class="kint">'+b.parentNode.outerHTML+"</div></body>"),a.document.close()},w=function(b){var a=
document.querySelector(".kint-focused");a&&l(a,"kint-focused");if(-1!==b){a=e[b];m(a,"kint-focused");var c=function(a){return a.offsetTop+(a.offsetParent?c(a.offsetParent):0)};window.scrollTo(0,c(a)-window.innerHeight/2)}f=b},x=function(b,a){b?0>--a&&(a=e.length-1):++a>=e.length&&(a=0);w(a);return!1};window.addEventListener("click",function(b){var a=b.target,c=a.nodeName.toLowerCase();if(t(a)){"dfn"===c?(g(a),a=a.parentNode):"var"===c&&(a=a.parentNode,c=a.nodeName.toLowerCase());if("li"===c&&"kint-tabs"===
a.parentNode.className)return"kint-active-tab"!==a.className&&(s(a),-1!==f&&u()),!1;if("nav"===c)return"footer"===a.parentNode.nodeName.toLowerCase()?(a=a.parentNode,k(a)?l(a):m(a)):setTimeout(function(){0<parseInt(a.a,10)?a.a--:(r(a.parentNode),-1!==f&&u())},300),b.stopPropagation(),!1;if(k(a,"kint-parent"))return p(a),-1!==f&&u(),!1;if(k(a,"kint-ide-link"))return b.preventDefault(),b=new XMLHttpRequest,b.open("GET",a.href),b.send(null),!1;if(k(a,"kint-popup-trigger")){b=a.parentNode;if("footer"===
b.nodeName.toLowerCase())b=b.previousSibling;else for(;b&&!k(b,"kint-parent");)b=b.parentNode;v(b)}}},!1);window.addEventListener("dblclick",function(b){var a=b.target;if(t(a)&&"nav"===a.nodeName.toLowerCase()){a.a=2;for(var c=document.getElementsByClassName("kint-parent"),d=c.length,a=k(a.parentNode);d--;)p(c[d],a);-1!==f&&u();b.stopPropagation()}},!1);window.onkeydown=function(b){if(b.target===document.body&&!b.altKey){var a=b.keyCode,c=b.shiftKey;b=f;if(68===a){if(-1===b)return u(),x(!1,b);w(-1);
return!1}if(-1!==b){if(9===a)return x(c,b);if(38===a)return x(!0,b);if(40===a)return x(!1,b);if(-1!==b){c=e[b];if("li"===c.nodeName.toLowerCase()){if(32===a||13===a)return s(c),u(),x(!0,b);if(39===a)return x(!1,b);if(37===a)return x(!0,b)}c=c.parentNode;if(32===a||13===a)return p(c),u(),!1;if(39===a||37===a){var d=k(c),a=37===a;if(d)r(c,a);else{if(a){do c=c.parentNode;while(c&&"dd"!==c.nodeName.toLowerCase());if(c){c=c.previousElementSibling;b=-1;for(d=c.querySelector("nav");d!==e[++b];);w(b)}else c=
e[b].parentNode}p(c,a)}u();return!1}}}}};window.addEventListener("load",function(){var b=Array.prototype.slice.call(document.querySelectorAll(".kint-microtime"),0);b.forEach(function(a){var c=parseFloat(a.innerHTML),d=Infinity,q=-Infinity;b.forEach(function(a){a=parseFloat(a.innerHTML);d>a&&(d=a);q<a&&(q=a)});a.style.background="hsl("+Math.round(120*(1-(c-d)/(q-d)))+",60%,70%)"})})};})()
