<?php
$settings = array(
	'enabled'           => Kint::$enabled,
	'displayCalledFrom' => Kint::$displayCalledFrom,
);

Kint::$enabled           = true;
Kint::$displayCalledFrom = false;
?>
<div class="kint kint-trace">
	<dl>
		<?php foreach ( $output as $i => $step ): ?>
		<dt class="kint-parent">
			<dfn><?php echo $i+1?></dfn>
            <span class="kint-plus _kint-collapse"></span>
			<var><?php if ( isset( $step['file'] ) ): ?>
			<?php echo self::shortenPath( $step['file'], $step['line'] ) ?>
			<?php else: ?>
			PHP internal call
			<?php endif ?></var>

			<?php echo $step['function']?>

			<?php if ( isset( $step['args'] ) ): ?>
			(<?php echo implode( ', ', array_keys( $step['args'] ) ) ?>)
			<?php endif?>
		</dt>
		<dd>
			<?php $firstTab = ' class="kint-active-tab"'?>
			<ul class="kint-tabs">
				<?php if ( isset( $step['source'] ) ): ?>
				<li<?php echo $firstTab?>>Source</li>
				<?php $firstTab = '' ?>
				<?php endif ?>

				<?php if ( !empty( $step['args'] ) ): ?>
				<li<?php echo $firstTab?>>Arguments</li>
				<?php $firstTab = '' ?>
				<?php endif ?>

				<?php if ( isset( $step['object'] ) ): ?>
				<?php $calleDump = kintParser::factory( $step['object'] );?>
				<li<?php echo $firstTab?>>Callee object [<?php echo $calleDump->subtype?> (<?php echo $calleDump->size?>)]</li>
				<?php $firstTab = '' ?>
				<?php endif ?>
			</ul><ul>
				<?php if ( isset( $step['source'] ) ): ?>
				<li>
					<pre class="kint-source"><?php echo $step['source'] ?></pre>
				</li>
				<?php endif ?>

				<?php if ( !empty( $step['args'] ) ): ?>
				<li>
					<?php
					foreach ( $step['args'] as $k=> $arg ) {
						echo self::$_richDecorator->decorate( kintParser::factory( $arg, $k ) );
					}
					?>
				</li>
				<?php endif ?>

				<?php if ( isset( $step['object'] ) ): ?>
				<li>
				<?php
					echo self::$_richDecorator->decorate( $calleDump );
				?>

				</li>
				<?php endif ?>
			</ul>
		</dd>
		<?php endforeach?>
	</dl>
</div>
<?php
Kint::$enabled           = $settings['enabled'];
Kint::$displayCalledFrom = $settings['displayCalledFrom'];
unset( $settings );
?>